image: golang:1.11.1-alpine
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: videocoin-183500
  GOPATH: /go/
  GOBIN: /go/bin
  GO111MODULE: "on"

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

before_script:
  - mkdir -p /go/src/gitlab.videocoin.io/videocoin /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.videocoin.io/videocoin/transcode
  - ln -s /go/src/gitlab.videocoin.io/videocoin /go/src/_/builds/videocoin
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa

stages:
  - build
  - publish

build-binary:
  stage: build
  script:
    - apk add --update make ca-certificates openssl python build-base alpine-sdk musl-dev musl
    - go version
    - update-ca-certificates
    - echo $GCLOUD_SA > ${HOME}/gcp_sa.json
    - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
    - google-cloud-sdk/bin/gcloud --quiet components update
    - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcp_sa.json
    - make deps
    - make package
    - export PATH=google-cloud-sdk/bin:$PATH
    - make publish
  only:
    - master
