apiVersion: skaffold/v1beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - deploy/skaffold/k8s-*
build:
  artifacts:
    - image: us.gcr.io/videocoin-183500/transcoder
  tagPolicy:
    gitCommit: {}
