apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: xcoders
          image: "{{ .Values.xcode.image.repository }}:{{ .Values.xcode.image.tag }}"
          imagePullPolicy: {{ .Values.xcode.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.xcode.service.internalPort }}
          env:
            - name: BASE_STREAM_URL
              value: http://ingest.videocoin.io:8080/hls
            - name: VERIFIER_URL
              value: http://verify.videocoin.io:8100
            - name: VERIFIER_RPC_ADDR
              value: verify.videocoin.io:50055
            - name: BASE_STORAGE_URL
              value: https://storage.googleapis.com/vc-test-fuse
            - name: FUSE_BUCKET
              value: vc-test-fuse
            - name: OUTPUT_DIR
              value: /opt/mnt/
            - name: MANAGER_RPC_ADDR
              value: api.videocoin.io:50051
            - name: BLOCKCHAIN_URL
              value: http://admin:LivePlanetS3cr3t@35.247.112.164
            - name: SMCA
              value: 0xEa91ac0B88F84e91e79Caa871d2EB04eF5133721
            - name: KEY_FILE
              value: keys/transcoder.key
            - name: PASSWORD
              value: transcoder