replicasCount: 1
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/transcoder
  tag: latest
  pullPolicy: Always

imageInit:
  repository: gcr.io/videocoin-network/transinit
  tag: latest
  pullPolicy: Always

config: {}

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 50

secrets:
  dbUri: ""
  mqUri: ""
  secret: ""
  sentryDsn: ""

resources:
  limits:
    cpu: 8
    memory: 8Gi 
  requests:
    cpu: 6
    memory: 8Gi
