xcode:
    image:
        repository: us.gcr.io/videocoin-183500/transcoder
        tag: latest
        pullPolicy: Always
    
    config: {}

    service:
        type: ClusterIP
        externalPort: 80
        internalPort: 80
    
    resources:
        limits:
        cpu: 200m
        memory: 200Mi
        requests:
        cpu: 200m
        memory: 200Mi
