apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-02-12T00:58:38Z"
  generation: 1
  labels:
    app: xcode
    chart: xcode-0.0.1
    heritage: Tiller
  name: xcode
  namespace: default
  resourceVersion: "30181"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/xcode
  uid: 554a030c-2e61-11e9-9dae-42010a8a0fcf
spec:
  selector:
    matchLabels:
      app: xcode
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xcode
      name: xcode
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: transcode
      containers:
        - env:
            - name: BASE_STORAGE_URL
              valueFrom:
                configMapKeyRef:
                  key: base_storage_url
                  name: config
            - name: BASE_STREAM_URL
              valueFrom:
                configMapKeyRef:
                  key: base_stream_url
                  name: config
            - name: BLOCKCHAIN_URL
              valueFrom:
                configMapKeyRef:
                  key: blockchain_url
                  name: config
            - name: SMCA
              valueFrom:
                configMapKeyRef:
                  key: smca
                  name: config
            - name: VERIFIER_URL
              valueFrom:
                configMapKeyRef:
                  key: verifier_url
                  name: config
            - name: FUSE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: fuse_bucket
                  name: config
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: nats_url
                  name: config
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: cluster_id
                  name: config
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: log_level
                  name: config
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transcode-password
                  key: password
            - name: HASH_KEY
              valueFrom:
                secretKeyRef:
                  name: secrethash
                  key: hash
            - name: NATS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: token
            - name: VERIFIER_RPC_ADDR
              value: verifier:50055
            - name: OUTPUT_DIR
              value: /opt/mnt/
            - name: MANAGER_RPC_ADDR
              value: manager:50051
            - name: KEY_FILE
              value: keys/transcoder.key
          image: us.gcr.io/videocoin-183500/transcoder:latest
          imagePullPolicy: Always
          name: xcoders
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 0
              cpu: 0
            limits:
              memory: 0
              cpu: 0
